import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '../components/AnimatedText'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={profilePic} alt="Yash Shah" className='w-full h-auto'></Image>
            </div>
            <div className='w-1/2'>
              
              <AnimatedText text="Tax inside out with EA Yash Shah" className='!text-6xl'/>
              <p>I am Yash Shah, an Enrolled Agent with a deep understanding of tax laws and financial planning. My passion lies in simplifying the complexities of taxes and providing personalized solutions to help individuals and businesses achieve their financial goals. Whether it’s tax preparation, resolving IRS issues, or creating strategies to maximize savings, I am committed to guiding you every step of the way. With my expertise and dedication, you can trust me to handle your taxes inside out, so you can focus on what truly matters.</p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
